# Generated by Django 2.1.2 on 2018-10-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misdoges', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perro',
        ),
    ]
