# Generated by Django 2.1.2 on 2018-10-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misdoges', '0004_auto_20181025_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('Rescatado', 'Rescatado'), ('Adoptado', 'Adoptado'), ('Disponible', 'Disponible')], max_length=15),
        ),
    ]
