# Generated by Django 2.1.2 on 2018-10-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misdoges', '0004_auto_20181025_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='id',
        ),
        migrations.AddField(
            model_name='perro',
            name='idperro',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('Adoptado', 'Adoptado'), ('Disponible', 'Disponible'), ('Rescatado', 'Rescatado')], max_length=15),
        ),
    ]
